# Generated by Django 5.2 on 2025-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Выберете дату и время начала привычки",
                        null=True,
                        verbose_name="Время начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Опишите действие вашей привычки",
                        max_length=300,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "rhythm",
                    models.CharField(
                        choices=[
                            ("every day", "каждый день"),
                            ("every other day", "чере день"),
                            ("every three days", "раз в 3 дня"),
                            ("every four days", "раз в 4 дня"),
                            ("every five days", "раз в 5 дней"),
                            ("every six days", "ра в 6 дней"),
                            ("every weak", "раз в неделю"),
                        ],
                        default="every day",
                        help_text="Выберите переодичностьт выполнения привычки",
                        max_length=16,
                        verbose_name="Переодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=300,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "lead_time",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите предположительное время выполнения привычки в минутах",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать для общего доступа",
                        verbose_name="Общий доступ",
                    ),
                ),
            ],
        ),
    ]
